### ISSUE TITLE
Outdated documentation at https://blueskyproject.io/hklpy

### ISSUE THREAD

**Issue by mrakitin** [bluesky/hklpy#109]
I am observing the outdated documentation for v0.3.14 at https://blueskyproject.io/hklpy while v0.3.15 is available. Was the documentation push failing?

![image](https://user-images.githubusercontent.com/13209176/109359927-49762e80-7854-11eb-9dba-51a5775866db.png)

**Comment by prjemian** [comment]
It's working now.
