### ISSUE TITLE
Extra diffractometer motors get set as `Kind.config`

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#110]
See https://github.com/APS-4ID-POLAR/ipython-polar/issues/103

**Comment by gfabbris** [comment]
Maybe this is part of the answer? https://github.com/bluesky/hklpy/blob/1ce145a4de8c3643a0df224c19eea309a84a8fe1/hkl/diffract.py#L206

Still not clear to me where it sets the other components to`Kind.config`.

**Comment by prjemian** [comment]
In the interest of releasing 0.3.16 this week, can we move this issue to the next milestone?

**Comment by gfabbris** [comment]
That's fine, the workaround seems to work.

**Comment by prjemian** [comment]
It's deep in `ophyd.device.Device.__set_kinds_according_to_list()` where the action takes place.  The content **is**managed by setting either `.`read_attrs` and /or `.configuration_attrs` so the responsibility for managing this in *hklpy* goes to the `Diffractometer` class.  Or to the subclass to specifically append to `.read_attrs`.

**Comment by prjemian** [comment]
Nothing to fix here?
