### ISSUE TITLE
problem with documentation publishing

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#124]
Public [documentation](https://blueskyproject.io/hklpy/) is not updated although GitHub publishing [action](https://github.com/bluesky/hklpy/runs/2392925730?check_suite_focus=true#step:10:105) says it has been pushed .  The new commits are seen in the documentation [repo](https://github.com/bluesky/bluesky.github.io).

**Comment by prjemian** [comment]
Looking at the [published docs repo](https://github.com/bluesky/bluesky.github.io), It's obvious now what is the problem.  They've been published with the wrong name: `${PACKAGE}`.

**Comment by prjemian** [comment]
Got toresolve this issue in the main branch since that is the only one that processes the publishing workflow.

**Comment by prjemian** [comment]
Once successful, delete the `${PACKAGE}` directory from the published docs repo.

**Comment by prjemian** [comment]
Ha!  *Delete the directory*, easier said than done.  Laborious process, deleting one-by-one from the web UI.

see, for instance: https://narayanatutorial.com/version-controls/git/how-to-delete-folder-in-github-repository-and-local-git-repository

**Comment by prjemian** [comment]
Too many files to do it by that method, each one a separate commit.

**Comment by prjemian** [comment]
@mrakitin : Agree with this procedure (to execute on my local workstation):

```sh
cd /tmp
git clone https://github.com/bluesky/bluesky.github.io
cd bluesky.github.io
/bin/rm -rf "\${PACKAGE}"
git commit -am "remove PACKAGE directory"
git push
cd ..
/bin/rm -rf bluesky.github.io
```

**Comment by prjemian** [comment]
Maybe needs a (temporary) deploy key first, to push from local command line?

**Comment by mrakitin** [comment]
@prjemian, in `/bin/rm -rf "\${PACKAGE}"`, why do you escape the `$`? Do you want this variable to be expanded?

**Comment by prjemian** [comment]
The repo:
![Clipboard02](https://user-images.githubusercontent.com/2279984/115459308-86bfc280-a1ec-11eb-8fbb-e0e5e48c1256.png)


It is necessary to delete the subdirectory with name exactly `${PACKAGE}` (not as a macro expansion)

```sh
(bluesky_2021_1) prjemian@zap:~/.../Bluesky/hklpy$ env | grep PACKAGE
(bluesky_2021_1) prjemian@zap:~/.../Bluesky/hklpy$ echo "${PACKAGE}"

(bluesky_2021_1) prjemian@zap:~/.../Bluesky/hklpy$ echo "\${PACKAGE}"
${PACKAGE}
```

**Comment by prjemian** [comment]
That thing circled in red must be deleted.

**Comment by mrakitin** [comment]
Oh, got it. How did it end up there?

**Comment by prjemian** [comment]
https://github.com/bluesky/hklpy/blob/05aa6fa62c53c35a391ce074cc31cc85007cc0da/.github/workflows/publish-docs.yml#L86

It's been there a while and we did not find it.

**Comment by prjemian** [comment]
Looks like a typo.  But, `${{ PACKAGE }}` was not the fix (because PACKAGE was not defined at that stage).  Not sure what fix to apply that would pick this up automatically, but the current change works.

**Comment by prjemian** [comment]
It's easy to overlook this type of thing that appears to be related to configuration or something else.

**Comment by mrakitin** [comment]
I think if you `export` it at around that line: https://github.com/bluesky/hklpy/blob/05aa6fa62c53c35a391ce074cc31cc85007cc0da/.github/workflows/publish-docs.yml#L30
that may appear in the environment variables in the last step. The Azure-like syntax would be `$(PACKAGE)`.

Can you try that?

**Comment by mrakitin** [comment]
I am referring to https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#runtime-expression-syntax. That may be different for GitHub Actions, but it's still M$, so hopefully it's consistent.

**Comment by mrakitin** [comment]
OK, I see the env. var `PACKAGE` was added to the env. Looking into https://docs.github.com/en/actions/reference/environment-variables, it seems we need to use:
```
${{ env.PACKAGE }}
```

**Comment by prjemian** [comment]
... As long as that definition is exactly the one we want.

**Comment by prjemian** [comment]
A good sign is that it did not fail the workflow right away (that's what a workflow syntax error looks like in the yaml file).

**Comment by prjemian** [comment]
Good.  This ran to completion.  Now, the only remaining item is to delete the directory named  `${PACKAGE}`.

**Comment by prjemian** [comment]
Using the [commands above](https://github.com/bluesky/hklpy/issues/124#issuecomment-823490034), deleted the offending directory in https://github.com/bluesky/bluesky.github.io/commit/5c92b9c61be17c84ea8024d0236192e430077574

**Comment by mrakitin** [comment]
The destination dir looks good now:
![image](https://user-images.githubusercontent.com/13209176/115468499-2be49600-a201-11eb-9966-3d61e871469c.png)

Thanks, @prjemian!
