### ISSUE TITLE
check_limits does not work well with pyHKL object

### ISSUE THREAD

**Issue by mrakitin** [bluesky/hklpy#13]
xref https://github.com/bluesky/bluesky/issues/1118.

**Comment by prjemian** [comment]
As @ambarb [noted](https://github.com/bluesky/bluesky/issues/1118#issuecomment-448275913):

> [`check_limits(scan(dets,tardis.l,-0.025,0.55,24, md={'purpose':'test L'}))` failed] because tardis.gamma was outside the range allowed

So check_limits((h,k,l)) would test that `tardis.calc.forward()` generates at least one solution to the given (*h,k,l)* reflection.  This would be applied, at least, at each end of the proposed range.  Deeper test would be at each reflection of the full trajectory.

**Comment by prjemian** [comment]
notes:

* https://blueskyproject.io/bluesky/simulation.html?highlight=check_limits#check-limits
* https://blueskyproject.io/bluesky/search.html?q=check_limits&check_keywords=yes&area=default
* https://github.com/bluesky/bluesky/blob/bdf2cdd73b971e543459f9182ed1595e134c06d7/bluesky/simulators.py#L83-L115

**Comment by prjemian** [comment]
For reciprocal space, we should compare the target tuple of (h, k, l) and assess if the real-space positions calculated by `calc.forward(h, k, l)` are within the real-space positioners' limits.

In `bluesky.simulators.check_limits()`, there is an assumption that every `set` message can call `msg.obj.limits` expecting a tuple of length 2.  If more than just one of `h`, `k`, or `l` are set, the `Diffractometer` returns a PseudoPos object with three tuples (e.g.: `FourcPseudoPos(h=(0,0), k=(0,0), l=(0,0))`).

This needs attention in both the `Diffractometer` class and also the `bluesky.simulators.check_limits()` function.

**Comment by prjemian** [comment]
Commit 1df6665 reformats existing code.
