### ISSUE TITLE
add recipe for conda-forge

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#136]
* https://conda-forge.org/#add_recipe
* https://github.com/conda-forge/staged-recipes
* https://github.com/conda-forge/hkl-feedstock
* https://github.com/nsls-ii-forge/?q=hkl
* https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-releases.html

**Comment by mrakitin** [comment]
We will take care of it with the SULI intern next week.

**Comment by mrakitin** [comment]
cc @kbeeperez

**Comment by prjemian** [comment]
Welcome @kbeeperez

**Comment by prjemian** [comment]
As [noted](https://github.com/conda-forge/staged-recipes/pull/15308#issuecomment-861930883):

> **Q**:  What's the best way to restart the CI for https://github.com/conda-forge/hklpy-feedstock?
> **A**:  Make an empty commit (`git commit -m 'Bump CI' --allow-empty`) and push.

And note this [how to trigger updates](https://github.com/conda-forge/hklpy-feedstock/commit/7f60447d44898de46f80a549e79e3c38f113b27f#commitcomment-52212414):

> NOTE: Please make sure to not push to the repository directly. Use branches in your fork (of **_hklpy-feedstock_**) for any changes and send a PR.

**Comment by prjemian** [comment]
@kbeeperez: Thanks for your work to resolve this issue!

**Comment by mrakitin** [comment]
> And note this [how to trigger updates](https://github.com/conda-forge/hklpy-feedstock/commit/7f60447d44898de46f80a549e79e3c38f113b27f#commitcomment-52212414):
> 
> > NOTE: Please make sure to not push to the repository directly. Use branches in your fork (of **_hklpy-feedstock_**) for any changes and send a PR.

We can actually add the `upload_on_branch: master` as documented here: https://conda-forge.org/docs/maintainer/conda_forge_yml.html#upload-on-branch. This is the feature that my SULI intern @buijennifer and I developed in 2019.
