### ISSUE TITLE
How to access the other libhkl engines such as incidence or Q?

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#138]
Such as the Engines under the E4CV documentation:
https://people.debian.org/~picca/hkl/hkl.html#org7ef08ba

**Comment by prjemian** [comment]
Looks as if one supplies the `engine="incidence"` kwarg when calling `hkl.calc.CalcRecip()`: https://github.com/bluesky/hklpy/blob/55696af396a654ca464642112c2031d7ec3551f9/hkl/calc.py#L122

This setting is locked from changes after the `Diffractometer()` object is created.

**Comment by gfabbris** [comment]
It looks like we can do something like `E4CV(..., engine='q',...)`:

https://github.com/bluesky/hklpy/blob/af126bdc60cca472a9fd3d4774555d77f8e341dc/hkl/diffract.py#L74

But when I tried,I got this kind of error:

```python
Subscription readback callback exception (EpicsMotor(prefix='gp:m4', name='fourc_tth', parent='fourc', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['user_offset', 'user_offset_dir', 'velocity', 'acceleration', 'motor_egu']))
Traceback (most recent call last):
  File "/home/apsu/Apps/miniconda3/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/home/apsu/Apps/miniconda3/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/pseudopos.py", line 687, in _real_pos_update
    self._update_position()
  File "/home/apsu/Apps/miniconda3/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/pseudopos.py", line 671, in _update_position
    calc_pseudo_pos = self.inverse(real_cur_pos)
  File "/home/apsu/Apps/miniconda3/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/pseudopos.py", line 188, in wrapped
    return method(self, pos, **new_kwargs)
  File "/home/apsu/Apps/miniconda3/envs/bluesky_2021_1/lib/python3.8/site-packages/hkl/diffract.py", line 274, in inverse
    return self.PseudoPosition(*self.calc.pseudo_positions)
TypeError: __new__() missing 2 required positional arguments: 'k' and 'l'
```

**Comment by gfabbris** [comment]
From Jong Woo Kim:

It looks like there is a way to add `h2, k2, l2, psi` parameters for the `psi_constant` mode. It seems to be handled by `fourc.engine.parameters_values_set`, but it's not clear how it works.

**Comment by gfabbris** [comment]
It looks like we sort of figured out how to set the parameters for the other modes of the `hkl` engine:

```python
from gi.repository import Hkl
fourc.calc.engine.mode = 'psi_constant'
fourc.calc.engine.parameters_values_set([1, 1, 0 , 10], Hkl.UnitEnum.USER)
```

But still not clear how to change the engine.

**Comment by prjemian** [comment]
Suggestion:

Look at this example (https://blueskyproject.io/hklpy/examples/notebooks/tst_e6c_test_calculations.html) that first creates a calc object.  Try declaring the engine like this example.  Later, the example connects that calc instance with a Diffractometer instance.

**Comment by prjemian** [comment]
"_Later_" (means: in some other example ... looking for that now).

**Comment by prjemian** [comment]
The example is in an archived notebook for the Tardis diffractometer.  Need
to extract that for you.

**Comment by gfabbris** [comment]
I think I understand the issue. Each engine needs a different set of pseudo-axis. In the example above, I had `h, k, l` setup as pseudo-axis, but `engine='q'` needs only a `q` pseudo-axis.

**Comment by prjemian** [comment]
The example I'm searching sets up a CalcRecip object first (with engine="hkl" in the example), then creates a Diffractometer and uses this previously-prepared calc object in place of the diffractometer.calc attribute.

**Comment by prjemian** [comment]
Here's how:

```python
import gi
gi.require_version('Hkl', '5.0')
from hkl.calc import A_KEV
from hkl.geometries import E4CV
from ophyd import Component
from ophyd import PseudoSingle
from ophyd import SoftPositioner

class FourcQ(E4CV):
    # one pseudo axis
    q = Component(PseudoSingle)
    
    # four real axes (MUST specify all canonical axes, in order expected by libhkl)
    omega = Component(SoftPositioner, init_pos=20)
    chi = Component(SoftPositioner, init_pos=90)
    phi = Component(SoftPositioner, init_pos=0)
    ttheta = Component(SoftPositioner, init_pos=40)

fcq = FourcQ("", name="fcq", calc_kw=dict(engine="q"))

# convert Q to angle
print(f"Q to angle: {fcq.forward(.01) = }")
print(f"angle to Q: {fcq.inverse(.5) = }")

fcq.wh()
fcq.move(1)
fcq.wh()
fcq.pa()

**Comment by prjemian** [comment]
I'll add an example notebook.

**Comment by prjemian** [comment]
Notebook needs some words surrounding the programming cells.

**Comment by prjemian** [comment]
Need to organize the documentation of the `calc` and `engine` modules so it is clearer how to provide easy access from the `diffract` module.

**Comment by prjemian** [comment]
Right now, there is no easy way to specify the engine in the class (using an attribute).  It would make this much easier for instrument scientists if this becomes definable at the attribute level.

**Comment by prjemian** [comment]
For example, this proposition:

```python
class FourcQ(Diffractometer):
    """E4CV (4-circle) geometry, using Q"""

    calc_class = calc.CalcE4CV
    calc_engine_name = "q"  # <---- NEW (default is "hkl")
```
