### ISSUE TITLE
prepare for v1.0.0 release

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#197]
See the process posted on the [Scientific Cookie Cutter](https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-releases.html) page.

First off, autocreate a list of milestone changes from commits, issues, PRs, & tags using [`create_release_notes.py`](https://github.com/prjemian/condatools/blob/main/create_release_notes.py) and post as a new page on the wiki following the index page on the [wiki](https://github.com/bluesky/hklpy/wiki/Release-Notes).  (Update this new page after the release is final but before closing the milestone.)

Update the `RELEASE_NOTES.rst` (per  `docs/source/release_notes.rst`) by selecting content from this list, per the cookie cutter instructions.  Then, continue that procedure.

**Comment by prjemian** [comment]
next: step 3 of https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-releases.html

```bash
git commit --allow-empty -m "REL: v1.0.0rc1"
git tag -a v1.0.0rc1
```

Verify correct version info

```bash
$ python ./setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'version': '1.0.0rc1', 'full-revisionid': '5e5389f7beab313ce2f4e62f0f4c0ed156270ed7', 'dirty': False, 'error': None}
Version: 1.0.0rc1
 full-revisionid: 5e5389f7beab313ce2f4e62f0f4c0ed156270ed7
 dirty: False

$ ipython
>>> import gi
>>> gi.require_version('Hkl', '5.0')
>>> import hkl
>>> hkl.__version__
v1.0.0rc1
```

Push to GitHub

```bash
git push origin main
git push origin v1.0.0rc1
```

**Comment by prjemian** [comment]
upload to PyPI

```bash
cd /tmp
git clone https://github.com/bluesky/hklpy
cd hklpy
python ./setup.py sdist
python ./setup.py bdist_wheel
twine upload dist/*
```

**Comment by prjemian** [comment]
@mrakitin Conda-forge will notice the new tag, check with PyPI, then build, test, and once that passes testing, publish the conda package automatically, right?

**Comment by mrakitin** [comment]
@prjemian, yes, that's the workflow. Maybe we'll need to merge that PR automatically if the automerge bot is not enabled there. Let's wait for the PR, and see if all requirements are there, and then will merge manually for now. Then I'll add bot-automerge.

**Comment by prjemian** [comment]
Your presentation last week was a big ➕

**Comment by prjemian** [comment]
@mrakitin : So far, the [hkl-feedstock](https://github.com/conda-forge/hkl-feedstock/) in conda-forge has not acted on this new tag.  What else needs to happen?

**Comment by mrakitin** [comment]
@prjemian, I guess it does not handle the rc versions automatically. Right now the latest tag on PyPI is 0.3.16 (https://pypi.org/project/hklpy/#history). Do you want to push v1.0.0 there?

**Comment by prjemian** [comment]
I will proceed with the v1.0.0 release ... tomorrow.

**Comment by prjemian** [comment]
Push [v1.0.0](https://pypi.org/project/hklpy/1.0.0/) to PyPI.  **Still**, the PyPI page says:

> The author of this package has not provided a project description

Despite this code in the project:

```python
(bluesky_2021_2) prjemian@zap:/tmp/hklpy$ grep description setup.py 
    description="Controls for using diffractometers within the Bluesky Framework: https://blueskyproject.io",
```


This is something to truly fix for v1.0.1.  Not a big deal.

**Comment by mrakitin** [comment]
I wonder if we also need the `long_description` field, read from `README.md` (with `long_description_content_type="text/markdown"`, see https://github.com/NSLS-II/scientific-python-cookiecutter/issues/25 for the discussion).

**Comment by prjemian** [comment]
Good point, I'll add that to (new) issue #202.
