### ISSUE TITLE
consider units for wavelength, energy, & lattice parameters

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#30]
As @ambarb [wrote](https://github.com/bluesky/hklpy/pull/23#discussion_r495454201):

> To answer @mrakitin question, maybe these are unit-UNaware values out of convenience.  I don't know the history.  But soft x-ray beamline uses **eV** so hard coding this here as **keV** is probably not the approach accepted in the development processs- but I was not involved so I cannot say.

**Comment by prjemian** [comment]
Perhaps a suggestion such as [this](https://github.com/bluesky/hklpy/issues/29#issuecomment-699514611) should be part of the documentation?

**Comment by ambarb** [comment]
If you mean the current units required, then I agree.

If you mean the history behind why these parameters appear unitless or that we may consider units for wavelength, energy, and lattice parameters, then maybe we should just wait and see how things shake out.  

If you want to reference this issue in the documentation, fine by me.

**Comment by prjemian** [comment]
Energy now has units in the Diffractometer class.  Wavelength is not represented there, only in the calc module.  The lattice parameters and the wavelength must have the same units (in the calc class) for compatibility with the underlying libhkl support.

It's not clear what action to take for this issue.   I'll close this issue on 2021-04-26 if there is no further comment.

**Comment by prjemian** [comment]
After this issue is closed, related comments could be added in a new issue (please reference this issue at that time).
