### ISSUE TITLE
link to published documentation

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#31]
The [`README.md` file](https://github.com/bluesky/hklpy/blob/master/README.md) needs a link to the URL where the documentation for this repo is published.

**Comment by mrakitin** [comment]
The old documentation was available in https://nsls-ii.github.io/hklpy/. I don't think it's up-to-date or is currently updating via CI, as the repo was moved to a new org.

**Comment by prjemian** [comment]
In #21, the documentation was brought up to date.  Can we get it published
now with the other bluesky documentation?
