### ISSUE TITLE
New default branch

### ISSUE THREAD

**Issue by mrakitin** [bluesky/hklpy#33]
I moved the default branch from `master` to `main`. See https://github.com/github/renaming for GitHub's plan on this. Please change your default local/remote branch to `main` and `<upstream/main>`.

Attn @ambarb, @prjemian

**Comment by prjemian** [comment]
Rename of default branch will also need to be configured on cloud support integrations such as travis-ci, RTD, Codacy, ... (whichever this repo uses).

**Comment by mrakitin** [comment]
Indeed. TravisCI does not seem to care, as the builds continue to run. We don't use RTD here, it'll be the https://blueskyproject.io/hklpy link served by github.io pages.
