### ISSUE TITLE
record wavelength as part of UB-defining reflections 

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#40]
The wavelength at which the r1/r2 were collected is not reported [in `pa()`]. It seems like the reflection does not hold the energy at which the angles were measured. Does the call to `compute_UB()` assume that the reflections were measured at the current energy?

_Originally posted by @gfabbris in https://github.com/BCDA-APS/apstools/issues/434#issuecomment-700923902_

**Comment by prjemian** [comment]
Would this addition be a breaking change?  Definitely should be part of the 1.0.0 release.

**Comment by ambarb** [comment]
I was about to add this to our ophyd object by hand at CSX now so that the wavelength is in the descriptors documents.  100% agree it should automatically be recorded in database.  Are you thinking descriptors?

**Comment by prjemian** [comment]
If we store it in the descriptors (as in #50), hklpy can control how it is named.  That is important for metadata search.

**Comment by ambarb** [comment]
so you are suggesting that it be define in the variable like `r1`, which is an argument to 
`compute_UB(r1, r2)` where currently `r1` contains just the hkl index values and motor positions?

If yes, this seems like replicating information that isn't strictly needed to compute the UB.  It is like spec in that regard. DOesn't matter what LAMBDA IS when you set the UB, it just matters what LAMDA is when you want to drive somewhere.

**Comment by prjemian** [comment]
Right, the UB is independent of wavelength.  The lambda should be part of each reflection (wavelength and angles) that was used to compute the UB.  Is that necessary to store (as SPEC does)?

**Comment by ambarb** [comment]
Spec's record isn't full proof though.  It assumes you have the LAMDBA set correctly for the reflections you are entering.

I think it matters more if you are trying to look up reflections and understand what energy they were found out.  I am not sure book-keeping that in this way is ok burden on the user.  Because then you maybe want to know which scan was the final reflection positions decided and what was its intensity.  Maybe a special plan to record this is a better approach?   Maybe more thinking and testing is needed.  

For what is available now, this just make the files we have to trace this information harder to read and add that on top of remote operations, and I really think it is too much information.

**Comment by ambarb** [comment]
because we don't trust in the ability to retrieve the correctly define variable in a python session that was accidentally closed or crashed -  thus the book-keeping file that is a step backwards from spec

**Comment by prjemian** [comment]
The underlying *libhkl* (as I'm calling the C code now) stores wavelength in the *geometry*.  The *hklpy* package accesses libhkl for any information about the reflection.  I'm thinking that hklpy needs to store the full set of information provided by the user at the time the reflection was defined (see #75) since there seems to be no easy way to recover that later.  This is the full set of information for each reflection that will be saved in the descriptor so that it can be recovered later to resume or repeat a scan.

**Comment by prjemian** [comment]
Also need to record the order of the two orientation reflections.  Rather than assuming the order (such as a list), add an additional key that describes whether reflection 1, 2, or none.

The case of computing **UB** with more than 2 reflections is described in the [libhkl documentation](https://people.debian.org/~picca/hkl/hkl.html#) (*simplex computation with more than 2 reflections using the GSL library*) but not yet supported in the *hklpy* code.  This code should be revised as the *simplex* technique is supported in *hklpy*.
