### ISSUE TITLE
rename Sphinx documentation directory

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#51]
Change from `doc` (singular) to the more common `docs` (plural).

**Comment by prjemian** [comment]
@mrakitin What integrations need to be adjusted for this change?

**Comment by mrakitin** [comment]
I don't think we need to change a lot besides the changes in the corresponding PR.

**Comment by prjemian** [comment]
Great.  How are the docs published?  Will they pick up this change automatically?

**Comment by mrakitin** [comment]
Maybe. The deployment step is handled by https://github.com/bluesky/hklpy/blob/0eba82acad32f1539e773b72163a0537117c1169/.travis.yml#L82, but there is no explicit link for the `doc` or `docs`. Worth experimenting.

**Comment by prjemian** [comment]
Good.  We'll drive on as planned.
