### ISSUE TITLE
Switch the CI from travis to Github Actions

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#53]
... whatever the other bluesky projects are using now.

* [x] setup CI process
* [x] build for all python versions ['3.6', '3.7', '3.8']
* [x] CI status: badging
* [x] drop travis-ci

**Comment by prjemian** [comment]
Dropping travis now.

**Comment by prjemian** [comment]
@mrakitin : Can you assist?  CI fails because it needs the hkl compiled code.  Do we need to build that here or is there a shortcut?

```
hkl/tests/test_tardis.py:9: in <module>
    gi.require_version('Hkl', '5.0')
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/gi/__init__.py:126: in require_version
    raise ValueError('Namespace %s not available' % namespace)
E   ValueError: Namespace Hkl not available
```

**Comment by mrakitin** [comment]
Was the `hkl` package installed from conda? This is a hard step. Installing `hklpy` on top of it is a piece of cake.

**Comment by prjemian** [comment]
All of this would be a piece of cake to use conda.  I'll switch to that.  It's just testing.  No need to raise artificial roadblocks.

**Comment by prjemian** [comment]
@danielballan : Thanks for the tip!

> [Debug your GitHub Actions by using tmate](https://github.com/marketplace/actions/debugging-with-tmate)

**Comment by prjemian** [comment]
@danielballan @mrakitin : A victory found while using tmate!  Tests were failing becuase the package being tested must be _installed_ into the conda environment: `pip install -e .`

This because some of the tests must be run as independent python code.  The independent tests, in `test_extra_motor.py`, are run as standalone python programs, not as test functions within the test file.

**Comment by danielballan** [comment]
Ah, I have tripped over this one myself time and time again. It can be surprising when pytest “works” on an uninstalled package, but with some important differences, including this one.
