### ISSUE TITLE
check Component hinting in the examples

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#61]
Per https://github.com/bluesky/hklpy/pull/52#discussion_r540347906

**Comment by prjemian** [comment]
Per @ambarb's [comment](https://github.com/bluesky/hklpy/pull/52#discussion_r545439301):

> I am also interested in this. Everything should always be normal, but I think people may want a variable "hinted" depending - if used as scan motor, yes plot, if not used as a scan motor, then probably most people don't want to see it in live plot.

**Comment by prjemian** [comment]
In the interest of releasing 0.3.16 this week, can we move this issue to the next milestone?

**Comment by ambarb** [comment]
fine by me.  I want to check some stuff at CSX to understand why we see so many things pop-up.  I think the hard part here is if it is in LIveTable then it is also in LivePlot.  IF you kill a scan, LiveTable may make it easier to trace back how to reset things. For example, plotting `diffractometer.h` versus `diffractometer.k` is kinda useless but nice to see in the LiveTable

**Comment by prjemian** [comment]
Short discussion today at the weekly coalition call, terse summary of my notes:

* `hinted` should be applied to the most notable thing in the device
* rely on the `labels` kwarg for groupings
* readouts are likely: `kind="hinted"`
* A good common pattern for any positioner:  `self.readback.name = self.name`
* only a few Components will have `kind="normal"`, fewer are `kind="hinted"`

```
    energy_units = Cpt(Signal, value="keV")  add  kind="config"
    energy_offset = Cpt(Signal, value=0)  add  kind="config"
    energy_update_calc_flag = Cpt(Signal, value=True)  add  kind="omitted"
```

**Comment by ambarb** [comment]
so everything pops up at CSX, because all motors (and the h, k and l objects) are in the detector list.  These things must be in the detector list so that we can use libarries like skbeam.recip or "re-calculate" hkl if we want to change orientation matrix (so data is still good, just not preceisily correct)

**Comment by prjemian** [comment]
The comment [cited](https://github.com/bluesky/hklpy/pull/52#discussion_r540347906) is no longer relevant due to subsequent revisions.  However, the overall review of use of the `kind` kwarg is relevant.  Expanding this issue beyond just the examples.
