### ISSUE TITLE
Resolve th angle mismatch for (113): mode? constraints?

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#66]
@ambarb : Found the FIXME item in `tst_e4cv_fourc.ipynb`:

```
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ git grep FIXME | grep examples/
examples/archive/e6c_sixc.ipynb:    "# FIXME:  must get same numbers, probably in different rows\n",
examples/archive/hkl-example.ipynb:    "# FIXME: So far, only works when previous constraints are removed.  Wrong mode?\n",
examples/archive/hkl-example.ipynb:    "# FIXME: pick mode\n",
examples/archive/tardis_example.ipynb:    "# FIXME: hack to get around what should have been done at init of tardis_calc instance\n",
examples/archive/tardis_example.ipynb:    "    # energy=tardis_calc.energy, # FIXME: unexpected keyword argument\n",
examples/tst_e4cv_fourc.ipynb:    "# FIXME: (113) `th` values do not match."
```

_Originally posted by @prjemian in https://github.com/bluesky/hklpy/issues/52#issuecomment-748208500_

**Comment by ambarb** [comment]
```
examples/archive/tardis_example.ipynb:    "    # energy=tardis_calc.energy, # FIXME: unexpected keyword argument\n",
```

seems like an error from here.  it wasn't fixed when the library was update. at CSX we use `tardis.calc.energy` now

**Comment by prjemian** [comment]
@ambarb : That's right about any content in `examples/archive`.  It is saved here for reference but will be discarded prior to release of 1.0.0.

**Comment by prjemian** [comment]
In the example, both `th` AND `tth` values are off between E4CV (libhkl) and fourc (SPEC):

```
======= ===== ========= =========
(hkl)   motor E4CV      SPEC     
======= ===== ========= =========
(0 0 2) tth   47.83041  38.09875 
(0 0 2) th    23.99932  19.13350 
(0 0 2) chi   90.01350  90.01350 
(0 0 2) phi   0.00000   0.00000  
(1 1 3) tth   84.66259  65.64400 
(1 1 3) th    42.33129  32.82125 
(1 1 3) chi   115.20291 115.23625
(1 1 3) phi   48.13306  48.13150 
======= ===== ========= =========
```

**Comment by prjemian** [comment]
NOTE: We are trying to get E4CV to match the SPEC values.

**Comment by prjemian** [comment]
But this particular comparison uses SPEC's **UB** matrix with the **E4CV** (and *libhkl*) code to compute the forward reflections.  The result does not match, as shown.

**Comment by prjemian** [comment]
Set the calculation mode back to `bissector` and wrote a note explaining that the UB matrix can't just be copied and re-used.  Need to compute UB from the supplied reflection angles (which is why the orientation reflection data must also be written into run, per #50).

**Comment by ambarb** [comment]
I've been able to do this for spec's sixc and E6C for a real crystal.  But I never copy the UB back and forth.  I enter the reflections into both programs.

I did not appreciate the mode changing needing to re-initialize the computation in hklpy.  Is this what you are saying?

**Comment by prjemian** [comment]
The mode is only needed for computing the forward reflection (hkl -> angles).  The U matrix is intrinsic to the  diffractometer's rotations and how they map onto the coordinate system (where are x, y, and z pointing).  Thus, UB can't be simply copied from SPEC to hklpy with any expectation of it working properly. (The example proves this naive approach will fail.)

**Comment by ambarb** [comment]
Ok.  That is important to understand.  @stuwilkins developed a Laue program that provides a UB matrix that CAN BE copied into spec.  This was required because the mounting of the sample was critical because of the limited degrees of freedom and made the users' homework prior to beam time much easier. 

What is the feeling that we need to put this aspect on issues for a community discussion?

**Comment by prjemian** [comment]
It is worthwhile. This is not the only instrument with this pattern.
Offline orientation can make the bean time more efficient.
