### ISSUE TITLE
Release process for v0.3.15

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#70]
The hklpy package is ready for 0.3.15 release.  What is the procedure to tag and release (including publishing conda & pip builds)?

**Comment by prjemian** [comment]
Bluesky packages normally follow this procedure:
https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-releases.html

**Comment by prjemian** [comment]
Need release notes (issue #71, PR #73)

**Comment by prjemian** [comment]
Also needed to add version number into the package, per #74.

**Comment by prjemian** [comment]
Tag and confirm local repo clone has the new version number.

```
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ git status
On branch main
Your branch is up-to-date with 'origin/main'.
nothing to commit, working directory clean
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ git pull
Already up-to-date.
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ git commit --allow-empty -m "REL: v0.3.15"
[main 101b8ea] REL: v0.3.15
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ git tag -a v0.3.15
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ python ./setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'version': '0.3.15', 'full-revisionid': '101b8ea00cb6c9d082ef4ffd322aac6faca70853', 'dirty': False, 'error': None}
Version: 0.3.15
 full-revisionid: 101b8ea00cb6c9d082ef4ffd322aac6faca70853
 dirty: False
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ ipython
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import gi
   ...: gi.require_version("Hkl", "5.0")

In [2]: import hkl

In [3]: hkl.__version__
Out[3]: '0.3.15'

In [4]: exit
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ 
```

**Comment by prjemian** [comment]
Push the new tag:

```
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ git push origin main
Counting objects: 1, done.
Writing objects: 100% (1/1), 191 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/bluesky/hklpy
   040766d..101b8ea  main -> main
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ git push origin v0.3.15
Counting objects: 1, done.
Writing objects: 100% (1/1), 191 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/bluesky/hklpy
 * [new tag]         v0.3.15 -> v0.3.15
```

**Comment by prjemian** [comment]
[On the GitHub GUI, edit the new tag](https://github.com/bluesky/hklpy/releases/new?tag=v0.3.15#) to be a release.

**Comment by prjemian** [comment]
Publish to PyPI (from a fresh repo clone in a /tmp directory):

```
cd /tmp
git clone https://github.com/bluesky/hklpy
cd hklpy
python3 setup.py sdist bdist_wheel
twine upload dist/*
```

**Comment by prjemian** [comment]
Missing required package meta-data:

```
(bluesky_2021_1) prjemian@poof /tmp/hklpy $ python3 setup.py sdist bdist_wheel
running sdist
running egg_info
creating hklpy.egg-info
writing hklpy.egg-info/PKG-INFO
writing dependency_links to hklpy.egg-info/dependency_links.txt
writing top-level names to hklpy.egg-info/top_level.txt
writing manifest file 'hklpy.egg-info/SOURCES.txt'
reading manifest file 'hklpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hklpy.egg-info/SOURCES.txt'
running check
warning: Check: missing required meta-data: url

warning: Check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating hklpy-0.3.15
creating hklpy-0.3.15/hkl
creating hklpy-0.3.15/hkl/tests
```

Should have found that out BEFORE tagging.  Now, need to delete the tag before proceeding.

**Comment by prjemian** [comment]
Here's the text added to the release:

bug fixes and documentation (including examples)

* [Change History](https://github.com/bluesky/hklpy/blob/main/docs/source/release_notes.rst)
* [Table of Tags, PRs, Issues, Commits](https://github.com/bluesky/hklpy/wiki/release-notes-0.3.15)

**Comment by prjemian** [comment]
Deleted release and tag from Github, and locally.

**Comment by prjemian** [comment]
```
git status
git pull
git commit --allow-empty -m "REL: v0.3.15"
git tag -a v0.3.15
python ./setup.py version
git push origin main
git push origin  v0.3.15
```

Now in `/tmp`:

```
pushd /tmp
/bin/rm -rf ./hklpy
git clone https://github.com/bluesky/hklpy
cd hklpy/
python3 setup.py sdist bdist_wheel
NO: twine upload dist/*
```

but

> warning: Check: missing meta-data: if 'maintainer' supplied, 'maintainer_email' must be supplied too

**Comment by prjemian** [comment]
Again

```
git status
git pull
git commit --allow-empty -m "REL: v0.3.15"
git tag -a v0.3.15
python ./setup.py version
git push origin main
git push origin  v0.3.15
```

Now in `/tmp`:

```
pushd /tmp
/bin/rm -rf ./hklpy
git clone https://github.com/bluesky/hklpy
cd hklpy/
python3 setup.py sdist bdist_wheel
```

Good.  No squawking from the `setup.py` builds.  Proceeding to upload...

```
twine upload dist/*
```

BUT this failed:

```
(bluesky_2021_1) prjemian@poof /tmp/hklpy $ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading hklpy-0.3.15-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26.7k/26.7k [00:00<00:00, 37.6kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
The user 'Pete.R.Jemian' isn't allowed to upload to project 'hklpy'. See https://pypi.org/help/#project-name for more information.
```

**Comment by prjemian** [comment]
@mrakitin : Can you add me to the [list of allowed _hklpy_ maintainers on PyPI](https://pypi.org/project/hklpy/)?

**Comment by prjemian** [comment]
Detailed release notes [generated by a script](https://github.com/prjemian/condatools/blob/main/create_release_notes.py) and copied to [wiki](https://github.com/bluesky/hklpy/wiki/release-notes-v0.3.15):

```
(bluesky_2021_1) prjemian@poof /tmp/hklpy $ /home/prjemian/Documents/projects/condatools/create_release_notes.py --head main v0.3.14 0.3.15 d1e35d8e8384087845d93ed8d7df8f96464a7138 | tee /tmp/notes.md 
```

**Comment by mrakitin** [comment]
> @mrakitin : Can you add me to the [list of allowed _hklpy_ maintainers on PyPI](https://pypi.org/project/hklpy/)?

Done.

**Comment by mrakitin** [comment]
> Detailed release notes [generated by a script](https://github.com/prjemian/condatools/blob/main/create_release_notes.py) and copied to [wiki](https://github.com/bluesky/hklpy/wiki/release-notes-v0.3.15):
> 
> ```
> (bluesky_2021_1) prjemian@poof /tmp/hklpy $ /home/prjemian/Documents/projects/condatools/create_release_notes.py --head main v0.3.14 0.3.15 d1e35d8e8384087845d93ed8d7df8f96464a7138 | tee /tmp/notes.md 
> ```

I like the detailed output. One comment: I noticed that the dates associated with the PRs in the corresponding table display either 2020-12-19 or 2020-12-20. Some PRs were merged or closed much earlier. Why the dates are so recent?

**Comment by prjemian** [comment]
That's a good eye for detail. The script must be picking the wrong date for
the prs. I'll fix that and regenerate the notes.

**Comment by prjemian** [comment]
Now, pushed to pypi using `twine` as shown above.

@mrakitin How do the conda packages get built and published?

**Comment by prjemian** [comment]
You had said (on Slack):

> The conda one (both nsls2forge and conda-forge) should pick it up by the auto-tick-bot

What's an auto-tick-bot?  This? https://github.com/regro/autotick-bot

**Comment by prjemian** [comment]
One would think that [`pull.last_modified`](https://github.com/prjemian/condatools/blob/8769fc69cd94d57c407f806fdeec337b7691ee94/create_release_notes.py#L247) would get the data the PR was merged or closed.  Obviously not the case.

```python
        print("pull request | date | state | title")
        print("-" * 5, " | ", "-" * 5, " | ", "-" * 5, " | ", "-" * 5)
        for k, pull in sorted(pulls.items(), reverse=True):
            state = {True: "merged", False: "closed"}[pull.merged]
            when = str2time(pull.last_modified).strftime("%Y-%m-%d")
            print(
                f"[#{pull.number}]({pull.html_url}) | {when} | {state} | {pull.title}"
            )
```

**Comment by prjemian** [comment]
Dates in the [*Table of Tags, PRs, Issues, & Commits*](https://github.com/bluesky/hklpy/wiki/release-notes-v0.3.15) are fixed now.

**Comment by prjemian** [comment]
I'll close this issue (and milestone and project) once I see the conda package is built and published.

**Comment by mrakitin** [comment]
> Now, pushed to pypi using `twine` as shown above.
> 
> @mrakitin How do the conda packages get built and published?

Thanks. See https://github.com/nsls-ii-forge/hklpy-feedstock/pull/2 for the auto-generated PR. I will add missing dependencies later.

**Comment by prjemian** [comment]
It's missing *pint*, see https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=5952&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=689, for units conversion

**Comment by mrakitin** [comment]
> You had said (on Slack):
> 
> > The conda one (both nsls2forge and conda-forge) should pick it up by the auto-tick-bot
> 
> What's an auto-tick-bot? This? https://github.com/regro/autotick-bot

Yes, that's conda-forge's bot. However, I noticed we are missing the `hklpy` feedstock in the `conda-forge` channel: https://github.com/conda-forge/?q=hkl&type=&language= (it's only the `hkl` one we are both are maintainers of).

**Comment by mrakitin** [comment]
> It's missing _pint_, see https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=5952&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=689, for units conversion

It should be addressed via https://github.com/nsls-ii-forge/pint-feedstock/pull/1.

**Comment by mrakitin** [comment]
> Dates in the [_Table of Tags, PRs, Issues, & Commits_](https://github.com/bluesky/hklpy/wiki/release-notes-v0.3.15) are fixed now.

Great, the dates look better now.

**Comment by mrakitin** [comment]
This is merged after a successful build: https://github.com/nsls-ii-forge/hklpy-feedstock/pull/2. The resulted package should be uploaded to https://anaconda.org/nsls2forge/hklpy shortly.

**Comment by mrakitin** [comment]
![image](https://user-images.githubusercontent.com/13209176/102787124-9201ff00-436e-11eb-8629-1d244a2108a8.png)

**Comment by prjemian** [comment]
Thanks!

**Comment by prjemian** [comment]
All complete.  Thanks @mrakitin, @ambarb, @stuartcampbell, and others for the contributions and effort!
